#version: '3'
#services:
#  database:
#    container_name: "mydb"
#    image: mysql
#    restart: always
#    environment:
#     MYSQL_ROOT_PASSWORD: root
#     MYSQL_PASSWORD: password
#     MYSQL_USER: user
#     MYSQL_DATABASE: solvro
#    ports:
#    - "3306:3306"
#  api:
#    build: .
#    ports:
#    - "8080:8080"
#    restart: always
#    depends_on:
#    - database
#
#version: "2.1"
#services:
#  api:
#    build: .
#    container_name: api
#    ports:
#    - "8080:8080"
#    depends_on:
#      - db
#
#  db:
#    container_name: db
#    image: mysql
#    ports:
#    - 3306
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_USER: "user"
#      MYSQL_PASSWORD: "password"
#      MYSQL_DATABASE: "solvro"

version: '3.3'
services:
  spring-boot:
    build: .
    depends_on:
    - db
    ports:
    - 8080:8080
  db:
    container_name: db
    image: mysql
    ports:
     - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "solvro"




